spring.application.name=pawinder
#spring.datasource.url=jdbc:mysql://mysql-pawinder-pawinderbd.b.aivencloud.com:18521/pawinder?ssl-mode=REQUIRED
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
server.port=${PORT:8080}
catapi.key=${CAT_API_KEY}
dogapi.key=${DOG_API_KEY}