spring.application.name=pawinder_server
spring.datasource.url=jdbc:mysql://localhost:3306/pawinder
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none

catapi.key=live_9ETW7SIaVi24B00KBiCJjxjdyIEIW62oa3oZpQ6mrh3bVHyf0DGyNutuufDs42Qf
dogapi.key=live_gK47Z9XMlntdelO904ckcPIxnevtMtIaZ3LFmkZHKyfET4EZYTJW2rc1nE2REyrM